version: '3.4'
services:
  apache-service:
    volumes:
       - ${WEBRROOT_HOST}:${WEBROOT_CONATINER}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
  php-service:
    volumes:
       - ${WEBRROOT_HOST}:${WEBROOT_CONATINER}